<!DOCTYPE html>
<html>

	<head>
	</head>

	<body>

		<section>
			<h1>Mon Panier</h1>
			<form action="#" method="">
				
				<div style="display: inline-block;">

					<span>Prix total panier : </span>
					<br><button style="margin-bottom: 15px;" type="submit">Acheter tout panier</button>
					<br>
					<div id="article" style="border: 1px solid; 
												padding: 40px;
												width: 100px;
												height: 100px;">
						<p style="text-align: center;">Image Article</p>
					</div>
					<select>
						<option selected>value bd</option>
						<option>0</option>
						<option>1</option>
						<option>2</option>
						<option>3</option>
						<option>4</option>
						<option>5</option>
						<option>6</option>
						<option>7</option>
						<option>8</option>
						<option>9</option>
						<option>10</option>
					</select>
					<br><button type="submit">Modifier Quantite</button>
					<br><button style="margin-bottom: 15px;" type="submit">Supprimer Article</button>
					<br><br><span>Prix de l'article : </span>
					<br><button style="margin-bottom: 15px;" type="submit">Acheter Article</button>

					<div id="article" style="border: 1px solid; 
												padding: 40px;
												width: 100px;
												height: 100px;">
						<p style="text-align: center;">Image Article</p>
					</div>
					<select>
						<option selected>value bd</option>
						<option>0</option>
						<option>1</option>
						<option>2</option>
						<option>3</option>
						<option>4</option>
						<option>5</option>
						<option>6</option>
						<option>7</option>
						<option>8</option>
						<option>9</option>
						<option>10</option>
					</select>
					<br><button type="submit">Modifier Quantite</button>
					<br><button style="margin-bottom: 15px;" type="submit">Supprimer Article</button>
					<br><br><span>Prix de l'article : </span>
					<br><button style="margin-bottom: 15px;" type="submit">Acheter Article</button>

					<div id="article" style="border: 1px solid; 
												padding: 40px;
												width: 100px;
												height: 100px;">
						<p style="text-align: center;">Image Article</p>
					</div>
					<select>
						<option selected>value bd</option>
						<option>0</option>
						<option>1</option>
						<option>2</option>
						<option>3</option>
						<option>4</option>
						<option>5</option>
						<option>6</option>
						<option>7</option>
						<option>8</option>
						<option>9</option>
						<option>10</option>
					</select>
					<br><button type="submit">Modifier Quantite</button>
					<br><button style="margin-bottom: 15px;" type="submit">Supprimer Article</button>
					<br><br><span>Prix de l'article : </span>
					<br><button style="margin-bottom: 15px;" type="submit">Acheter Article</button>

				</div>

				<div style="display: inline-block;">

					<div id="article" style="border: 1px solid; 
												padding: 40px;
												width: 100px;
												height: 100px;">
						<p style="text-align: center;">Image Article</p>
					</div>
					<select>
						<option selected>value bd</option>
						<option>0</option>
						<option>1</option>
						<option>2</option>
						<option>3</option>
						<option>4</option>
						<option>5</option>
						<option>6</option>
						<option>7</option>
						<option>8</option>
						<option>9</option>
						<option>10</option>
					</select>
					<br><button type="submit">Modifier Quantite</button>
					<br><button style="margin-bottom: 15px;" type="submit">Supprimer Article</button>
					<br><br><span>Prix de l'article : </span>
					<br><button style="margin-bottom: 15px;" type="submit">Acheter Article</button>

					<div id="article" style="border: 1px solid; 
												padding: 40px;
												width: 100px;
												height: 100px;">
						<p style="text-align: center;">Image Article</p>
					</div>
					<select>
						<option selected>value bd</option>
						<option>0</option>
						<option>1</option>
						<option>2</option>
						<option>3</option>
						<option>4</option>
						<option>5</option>
						<option>6</option>
						<option>7</option>
						<option>8</option>
						<option>9</option>
						<option>10</option>
					</select>
					<br><button type="submit">Modifier Quantite</button>
					<br><button style="margin-bottom: 15px;" type="submit">Supprimer Article</button>
					<br><br><span>Prix de l'article : </span>
					<br><button style="margin-bottom: 15px;" type="submit">Acheter Article</button>

					<div id="article" style="border: 1px solid; 
												padding: 40px;
												width: 100px;
												height: 100px;">
						<p style="text-align: center;">Image Article</p>
					</div>
					<select>
						<option selected>value bd</option>
						<option>0</option>
						<option>1</option>
						<option>2</option>
						<option>3</option>
						<option>4</option>
						<option>5</option>
						<option>6</option>
						<option>7</option>
						<option>8</option>
						<option>9</option>
						<option>10</option>
					</select>
					<br><button type="submit">Modifier Quantite</button>
					<br><button style="margin-bottom: 15px;" type="submit">Supprimer Article</button>
					<br><br><span>Prix de l'article : </span>
					<br><button style="margin-bottom: 15px;" type="submit">Acheter Article</button>

				</div>

				<div style="display: inline-block;">

					<div id="article" style="border: 1px solid; 
												padding: 40px;
												width: 100px;
												height: 100px;">
						<p style="text-align: center;">Image Article</p>
					</div>
					<select>
						<option selected>value bd</option>
						<option>0</option>
						<option>1</option>
						<option>2</option>
						<option>3</option>
						<option>4</option>
						<option>5</option>
						<option>6</option>
						<option>7</option>
						<option>8</option>
						<option>9</option>
						<option>10</option>
					</select>
					<br><button type="submit">Modifier Quantite</button>
					<br><button style="margin-bottom: 15px;" type="submit">Supprimer Article</button>
					<br><br><span>Prix de l'article : </span>
					<br><button style="margin-bottom: 15px;" type="submit">Acheter Article</button>

					<div id="article" style="border: 1px solid; 
												padding: 40px;
												width: 100px;
												height: 100px;">
						<p style="text-align: center;">Image Article</p>
					</div>
					<select>
						<option selected>value bd</option>
						<option>0</option>
						<option>1</option>
						<option>2</option>
						<option>3</option>
						<option>4</option>
						<option>5</option>
						<option>6</option>
						<option>7</option>
						<option>8</option>
						<option>9</option>
						<option>10</option>
					</select>
					<br><button type="submit">Modifier Quantite</button>
					<br><button style="margin-bottom: 15px;" type="submit">Supprimer Article</button>
					<br><br><span>Prix de l'article : </span>
					<br><button style="margin-bottom: 15px;" type="submit">Acheter Article</button>

					<div id="article" style="border: 1px solid; 
												padding: 40px;
												width: 100px;
												height: 100px;">
						<p style="text-align: center;">Image Article</p>
					</div>
					<select>
						<option selected>value bd</option>
						<option>0</option>
						<option>1</option>
						<option>2</option>
						<option>3</option>
						<option>4</option>
						<option>5</option>
						<option>6</option>
						<option>7</option>
						<option>8</option>
						<option>9</option>
						<option>10</option>
					</select>
					<br><button type="submit">Modifier Quantite</button>
					<br><button style="margin-bottom: 15px;" type="submit">Supprimer Article</button>
					<br><br><span>Prix de l'article : </span>
					<br><button style="margin-bottom: 15px;" type="submit">Acheter Article</button>

				</div>
	
			</form>	

		</section>	

	</body>

</html>

